[workspace]
members = [
  "contracts"
]

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

# [programs.devnet]
# escrow = "YOUR_PROGRAM_ID_HERE"

[scripts]
test = "mocha -t 1000000 tests/"

[toolchain]
anchor_version = "0.29.0"
