[programs.localnet]
funhi_escrow = "target/deploy/funhi_escrow-keypair.json"  # your compiled program keypair path

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
