[programs.localnet]
funhi_escrow = "path/to/target/deploy/funhi_escrow.so"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
